### ISSUE TITLE
Issues running example

### ISSUE THREAD

**Issue by s-e-schneider** [giovanni-bolcato/deepFMPOv3D#1]
Hi!

Thanks for the code, this sounds really interesting. I wanted to give the example a go, but I run into the following error:

`[...]
File "pandas/_libs/lib.pyx", line 2870, in pandas._libs.lib.map_infer
  File "[...]python/packages/deepFMPOv3D-main/./Modules/build_encoding.py", line 39, in get_similarity
    os.mkdir(str(smiles_name))
FileExistsError: [Errno 17] File exists: '[Yb]N1CCCCC1[Lu]'`

and there is an empty folder with the name '[Yb]N1CCCCC1[Lu]' in my directory. Am I doing something wrong?

**Comment by giovanni-bolcato** [comment]
hi! I will have a look and come back to you asap!
Giovanni

Il lun 14 mar 2022, 20:49 s-e-schneider ***@***.***> ha
scritto:

**Comment by giovanni-bolcato** [comment]
hi! I will have a look and come back to you asap!
Giovanni

Il lun 14 mar 2022, 20:49 s-e-schneider ***@***.***> ha
scritto:

**Comment by MKCarter** [comment]
Hi,

I have also tried running the example given. I appear to have a similar error to that detailed above. Here is the full error message:

```
Traceback (most recent call last):
  File "deepFMPO.py", line 63, in <module>
    main(fragment_file, lead_file, args)
  File "deepFMPO.py", line 33, in main
    encodings, decodings = get_encodings(fragments)
  File "./Modules/build_encoding.py", line 139, in get_encodings
    pairings, id_dict = get_hierarchy(fragments)
  File "./Modules/build_encoding.py", line 121, in get_hierarchy
    distance_matrix,  id_dict = get_dist_matrix(fragments)
  File "./Modules/build_encoding.py", line 56, in get_dist_matrix
    df["similarity_vector"] = ddf.map_partitions(function_for_dask,meta='float').compute(scheduler='processes')
  File "/Users/michaelcarter/miniconda3/envs/deepFMPO/lib//python3.7/site-packages/dask/base.py", line 290, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/Users/michaelcarter/miniconda3/envs/deepFMPO/lib//python3.7/site-packages/dask/base.py", line 573, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/Users/michaelcarter/miniconda3/envs/deepFMPO/lib//python3.7/site-packages/dask/multiprocessing.py", line 231, in get
    **kwargs,
  File "/Users/michaelcarter/miniconda3/envs/deepFMPO/lib//python3.7/site-packages/dask/local.py", line 506, in get_async
    raise_exception(exc, tb)
  File "/Users/michaelcarter/miniconda3/envs/deepFMPO/lib//python3.7/site-packages/dask/multiprocessing.py", line 110, in reraise
    raise exc
dask.multiprocessing.FileExistsError: [Errno 17] File exists: '[Yb]C1CCC([Lu])CC1'

Traceback
---------
  File "/Users/michaelcarter/miniconda3/envs/deepFMPO/lib//python3.7/site-packages/dask/local.py", line 219, in execute_task
    result = _execute_task(task, data)
  File "/Users/michaelcarter/miniconda3/envs/deepFMPO/lib//python3.7/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/Users/michaelcarter/miniconda3/envs/deepFMPO/lib//python3.7/site-packages/dask/optimization.py", line 969, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
  File "/Users/michaelcarter/miniconda3/envs/deepFMPO/lib//python3.7/site-packages/dask/core.py", line 149, in get
    result = _execute_task(task, cache)
  File "/Users/michaelcarter/miniconda3/envs/deepFMPO/lib//python3.7/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/Users/michaelcarter/miniconda3/envs/deepFMPO/lib//python3.7/site-packages/dask/utils.py", line 39, in apply
    return func(*args, **kwargs)
  File "/Users/michaelcarter/miniconda3/envs/deepFMPO/lib//python3.7/site-packages/dask/dataframe/core.py", line 6174, in apply_and_enforce
    df = func(*args, **kwargs)
  File "./Modules/build_encoding.py", line 52, in function_for_dask
    return df.smile.apply(get_similarity)
  File "/Users/michaelcarter/miniconda3/envs/deepFMPO/lib//python3.7/site-packages/pandas/core/series.py", line 4357, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/Users/michaelcarter/miniconda3/envs/deepFMPO/lib//python3.7/site-packages/pandas/core/apply.py", line 1043, in apply
    return self.apply_standard()
  File "/Users/michaelcarter/miniconda3/envs/deepFMPO/lib//python3.7/site-packages/pandas/core/apply.py", line 1101, in apply_standard
    convert=self.convert_dtype,
  File "pandas/_libs/lib.pyx", line 2859, in pandas._libs.lib.map_infer
  File "./Modules/build_encoding.py", line 39, in get_similarity
    os.mkdir(str(smiles_name))
```
Any ideas on how to resolve this? 

Many Thanks,
Mike
